matches = {
    "student_name": "\s*\"ctl00_lblUser\" title=\s*\".*\"><span style='font-size:9px'>(.*?)(?=</)",
    "student_id": "\s*\"ctl00_lblUser\" title=\s*\"(.*?)(?=\">)",
    "faculty": "\s*\"ctl00_cntphmaster_StudDataGeneralControl1_lblFaculty\">(.*?)(?=</)",
    "admission_year": "\s*\"ctl00_lblAdmYear\">(.*?)(?=</)",
    "current_semester": "\s*\"ctl00_lblAdmSem\">(.*?)(?=</)",
    "gender": "\s*\"ctl00_cntphmaster_StudDataGeneralControl1_StudentDtlPopup_ucStudDtlsTabsGnrlCtrl_TabHeader1_Tab_UcStudentBasicDataTabs_0_ucTabHeader_Tab_StudBasicData_View_0_lblGender\">(.*?)(?=</)",
    "nationality": "\s*\"ctl00_cntphmaster_StudDataGeneralControl1_StudentDtlPopup_ucStudDtlsTabsGnrlCtrl_TabHeader1_Tab_UcStudentBasicDataTabs_0_ucTabHeader_Tab_StudBasicData_View_0_lblFirstNationality\">(.*?)(?=</)",
    "national_id": "\s*\"ctl00_cntphmaster_StudDataGeneralControl1_StudentDtlPopup_ucStudDtlsTabsGnrlCtrl_TabHeader1_Tab_UcStudentBasicDataTabs_0_ucTabHeader_Tab_StudBasicData_View_0_txtNationalNum\" MaxLength=\s*\".*\">(.*?)(?=</)",
    "birth_date": "\s*\"ctl00_cntphmaster_StudDataGeneralControl1_StudentDtlPopup_ucStudDtlsTabsGnrlCtrl_TabHeader1_Tab_UcStudentBasicDataTabs_0_ucTabHeader_Tab_StudBasicData_View_0_txtBirthDate\">(.*?)(?=</)",
    "email": "\s*\"ctl00_cntphmaster_StudDataGeneralControl1_StudentDtlPopup_ucStudDtlsTabsGnrlCtrl_TabHeader1_Tab_UcStudentBasicDataTabs_0_ucTabHeader_Tab_StudBasicData_View_0_txtEmail\">(.*?)(?=</)",
    "mobile": "\s*\"ctl00_cntphmaster_StudDataGeneralControl1_StudentDtlPopup_ucStudDtlsTabsGnrlCtrl_TabHeader1_Tab_UcStudentBasicDataTabs_0_ucTabHeader_Tab_StudBasicData_View_0_txtMobileNo\">(.*?)(?=</)",
    "degree": "\s*\"ctl00_cntphmaster_StudDataGeneralControl1_lblScDegree\">(.*?)(?=</)",
    "student_major": "\s*\"ctl00_cntphmaster_StudDataGeneralControl1_lblMajior\">(.*?)(?=</)",
    "level": "\s*\"ctl00_cntphmaster_StudDataGeneralControl1_LblLvl\">(.*?)(?=</)",
    "enrollment_status": "\s*\"ctl00_cntphmaster_StudDataGeneralControl1_lblEnrollStatus\">(.*?)(?=</)",
    "academic_status": "\s*\"ctl00_cntphmaster_StudDataGeneralControl1_lblAcadmicStatus\">(.*?)(?=</)",
    "passed_ch": "\s*\"ctl00_cntphmaster_StudDataGeneralControl1_lblTotPassedCh\"\s*>\s*<\s*b\s*>\s*<\s*font\s*color\s*=\s*\"Black\"\s*>(.*?)(?=</)",
    "cgpa": "\s*\"ctl00_cntphmaster_StudDataGeneralControl1_lbLCGPA\"\s*>\s*<\s*b\s*>\s*<\s*font\s*color\s*=\s*\"Black\"\s*>(.*?)(?=</)",
    "notifications": "\s*\<LI>\s*\<.*?>(.*?)(?=</)",
    "courses_codes": "\s*\"ctl00_cntphmaster_grdAttendanceFW_ct.*_txtCourseCode\"\s.*>(.*?)(?=</)",
    "courses_names": "\s*\"ctl00_cntphmaster_grdAttendanceFW_ct.*_Label2\">(.*?)(?=</)",
    "absence_times": "\s*\"ctl00_cntphmaster_grdAttendanceFW_ct.*_Label3\">(.*?)(?=</)",
    "warnings": "\s*\"ctl00_cntphmaster_grdAttendanceFW_ct.*_Label4\">(.*?)(?=</)",
    "advisor_name": "\s*\"ctl00_cntphmaster_StudDataGeneralControl1_StudentDtlPopup_ucStudDtlsTabsGnrlCtrl_TabHeader1_Tab_UcStudentAcademicDataTabs_1_ucTabHeader_Tab_StudAcadData_View_0_LblAcadAdvisorName\">(.*?)(?=<\/)",
}
